### Get Blog articles
GET http://localhost:3003/api/blogs

### Create Blog article
POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplYW5zb2wzLnBhdHJlQG5lbnVwaGFyLmZyIiwidXNlcklkIjoiNjM0NWQyMGQwYThiNTIyYmFhM2U2N2RkIiwiaWF0IjoxNjY1NTI0MDUxfQ.RvhwVQqKcwJ_Fww0PXk8ktfElJJAnL7ujctZUh5LSoI

{
    "title": "Laborum cupidatat nostrud ullamco ad amet ut do.",
    "author": "Jean-Sol Patre",
    "url": "https://www.articlesbidons.fr/456123",
    "likes": 5
}

### Update likes of Blog article
PUT http://localhost:3003/api/blogs/633b525ab1ec8ce08ee1580a
Content-type: application/json

{
    "likes": "10s"
}

### Delete likes of Blog article
DELETE http://localhost:3003/api/blogs/6345e87ed4c0cfc7e4970b2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplYW5zb2wzLnBhdHJlQG5lbnVwaGFyLmZyIiwidXNlcklkIjoiNjM0NWQyMGQwYThiNTIyYmFhM2U2N2RkIiwiaWF0IjoxNjY1NTI0MDUxfQ.RvhwVQqKcwJ_Fww0PXk8ktfElJJAnL7ujctZUh5LSoI

