### Get Blog articles
GET http://localhost:3003/api/blogs

### Create Blog article
POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Laborum cupidatat nostrud ullamco ad amet ut do.",
    "author": "Jean-Sol Patre",
    "url": "https://www.articlesbidons.fr/456123",
    "likes": 5
}

### Update likes of Blog article
PUT http://localhost:3003/api/blogs/633b525ab1ec8ce08ee1580a
Content-type: application/json

{
    "likes": "10s"
}

### Update likes of Blog article
DELETE http://localhost:3003/api/blogs/633b525ab1ec8ce08ee1580a